sudo: require
dist: xenial
language: bash
if: tag IS present
notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - PDF_NAME=M19_SYLVAINMETAYER.pdf
    - PAPER_NAME=M19_SYLVAINMETAYER_PAPER.pdf
before_install:
  - sudo apt-get install -y --no-install-recommends texlive-full make python-pygments
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.cache/latex
  apt: true
before_script: cd $TRAVIS_BUILD_DIR/
script:
  - make && mv main.pdf $PDF_NAME
  - make clean && make paper && make && mv main.pdf $PAPER_NAME
deploy:
  - provider: releases
    skip_cleanup: true
    before_deploy: "make soft_clean"
    api_key:
      secure: $CI_TOKEN
    file:
      - ./$PDF_NAME
      - ./$PAPER_NAME
    on:
      branch: master
      tags: true

