sudo: require
dist: xenial
language: bash
if: tag IS present
env:
  global:
    - TODO_NAME=report_with_todo.pdf
    - PDF_NAME=M19_SYLVAINMETAYER.pdf
    - PAPER_NAME=M19_SYLVAINMETAYER_PAPER.pdf
    - SOUTENANCE_NAME=soutenance.pdf

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

before_script: cd $TRAVIS_BUILD_DIR/
script:
  - make docker-build && mv main.pdf $TODO_NAME
  - make removeComment
  - make docker-build && mv main.pdf $PDF_NAME
  - make paper
  - make docker-build && mv main.pdf $PAPER_NAME
  - make docker-soutenance && mv soutenance/main.pdf $SOUTENANCE_NAME

deploy:
  - provider: releases
    skip_cleanup: true
    before_deploy: "make soft_clean"
    api_key:
      secure: $CI_TOKEN
    file:
      - ./$PDF_NAME
      - ./$PAPER_NAME
      - ./$TODO_NAME
      - ./$SOUTENANCE_NAME
    on:
      branch: master
      tags: true

notifications:
  email:
    on_success: never
    on_failure: always

