sudo: require
dist: xenial
language: bash
if: tag IS present
env:
  global:
    - TODO_NAME=report_with_todo.pdf
    - PDF_NAME=M19_SYLVAINMETAYER.pdf
    - PAPER_NAME=M19_SYLVAINMETAYER_PAPER.pdf

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

cache:
  timeout: 1000
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  - mkdir -p $HOME/docker && docker save sylvainmetayer/latex-debian | gzip -2 > $HOME/docker/sylvainmetayer_latex_debian.tar.gz'

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_script: cd $TRAVIS_BUILD_DIR/
script:
  - make docker-build && mv main.pdf $TODO_NAME && make clean
  - make removeComment
  - make docker-build && mv main.pdf $PDF_NAME && make clean
  - make paper
  - make docker-build && mv main.pdf $PAPER_NAME

deploy:
  - provider: releases
    skip_cleanup: true
    before_deploy: "make soft_clean"
    api_key:
      secure: $CI_TOKEN
    file:
      - ./$PDF_NAME
      - ./$PAPER_NAME
      - ./$TODO_NAME
    on:
      branch: master
      tags: true

notifications:
  email:
    on_success: never
    on_failure: always

