sudo: require
dist: xenial
language: bash

addons:
  apt:
    packages:
      - texlive-full
      - make
      - python-pygments
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
  apt: true
before_script: cd $TRAVIS_BUILD_DIR/
script:
  - make computer
  - make build
  - mv main.pdf M19_SYLVAINMETAYER.pdf
  - make clean
  - make paper
  - make build # Now, we want to build the paper version, which has differents margins.
  - mv main.pdf M19_SYLVAINMETAYER_PAPER.pdf
deploy:
  - provider: releases
    skip_cleanup: true
    before_deploy: "make soft_clean"
    api_key:
      secure: $CI_TOKEN
    file:
      - ./M19_SYLVAINMETAYER.pdf
      - ./M19_SYLVAINMETAYER_PAPER.pdf
    on:
      branch: master
      tags: true
