sudo: require
dist: xenial
language: bash

env:
  global:
    - PDF_NAME=M19_SYLVAINMETAYER.pdf
    - PAPER_NAME=M19_SYLVAINMETAYER_PAPER.pdf
before_install:
  - sudo apt-get install -y --no-install-recommends texlive-full make python-pygments
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
  apt: true
before_script: cd $TRAVIS_BUILD_DIR/
script:
  - make computer && make build && mv main.pdf $PDF_NAME # PDF
  - make clean && make paper && make build && mv main.pdf $PAPER_NAME # Paper, with differents margins
deploy:
  - provider: releases
    skip_cleanup: true
    before_deploy: "make soft_clean"
    api_key:
      secure: $CI_TOKEN
    file:
      - ./$PDF_NAME
      - ./$PAPER_NAME
    on:
      branch: master
      tags: true

